services:
  - type: web
    name: cesapp-backend
    env: node
    region: oregon  # o usa ohaio si prefieres
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run dev
    envVars:
      - key: NODE_ENV
        value: production
